# Generated by Django 5.2.15 on 2026-06-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_theatre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('show_time', models.DateTimeField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.theatre')),
            ],
        ),
    ]
